### ISSUE TITLE
Inconsistent OpenKIM potentials in Potential and lammps_potential

### ISSUE THREAD

**Issue by jan-janssen** [lmhale99/potentials-library#1]
In the last commit the potentials in the `Potential` folder were updated:
https://github.com/lmhale99/potentials-library/commit/cc8e68f6e206ca1af0c4a4e7ea29fe44b93ef584
But those in `lammps_potential` are still outdated, e.g. using the older openKIM references.

**Comment by lmhale99** [comment]
Hi Jan,

The issue is more due to a conceptual difference with the KIM potential versions than the records not being fully updated.
- The different KIM versions are something in between the same and different implementation as any change to the code results in a version change, even if it was simply kim-api updates.
- The lammps_potential ids should be the full kim ids with version and details as each version can conceivably behave differently.
- The potential listing on the website is reduced down to a single entry using the shortcode (MO_123456789012) for conciseness and to reflect that version controlling is being handled by KIM.
- The NIST listings for the KIM models then only need to update the web links to the KIM pages for the different versions.  This could either be the newest known version, or a list of all known versions.
- Clicking on "compute properties" sends to the shortcode.html page, which then redirects to the fullid.html page for the largest version number.

Ideally, each version should be known and listed somewhere with computed properties for each available. The challenges with this are that
- The stuff at the beginning of the full KIM id is not the same for all versions. I don't have a way currently to scrape the old version ids.  A web scrape can work, just would take some time to set up.
- Each model version may be limited to certain kim-api versions, which in turn may be limited to certain LAMMPS versions. This may also be overkill if the old obsolete versions behave the same as the newer versions.  Even KIM themselves skip property evaluations on the older models.
- Related to the last one, a given LAMMPS version will limit the compatible KIM models and versions. Even using the latest stable LAMMPS, the KIM model versions that work with it are not all the newest. High-throughput calculations then either need to switch LAMMPS for the different KIM models or only consider the KIM models that are compatible with the current LAMMPS.

Figuring out the best way to handle this all will likely take a bit more work.

P.S. I just updated the repository with the newest potentials.
